repos:
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: poetry run autoflake
        args: [--in-place]
        language: system
        types: [python]
        require_serial: true
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
        require_serial: true
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        require_serial: true
